name: Integration CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Run
      run: docker compose -f docker-compose.yaml up -d

    - name: Teardown
      run: docker compose -f docker-compose.yaml down
