name: Integration CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: echo "AIRFLOW_UID=5000" > .env

    - name: Build and Run
      run: docker compose -f docker-compose.yaml up -d

    - name: Teardown
      run: docker compose -f docker-compose.yaml down

    - name: Logs on failure
      if: failure()
      run: docker compose logs

